### ISSUE TITLE
NHMD Entomology - Connecting multiple preparations

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Pinned-Insects-workstation#45] opened 2023-08-03 11:11 UTC
Many of single lepidoptera specimens are dually represented on pins as well as on slides that have been prepared of their genitalia. When a slide has been prepared from a pinned specimen, a label indicating this is present on the pin. This label contains the slide number. It is not clear if the slide number corresponds to an overall collection of slides for entomology, or if slides are renumbered for subcollections. Jan Pedersen mentioned that Ole Karsholt would know. 

Collections managers prefer that the slides and insects have the same catalog number. It would be optimal to be able to register the existence of the slide in the MADD App. 

THis could be done in the app once a standard is set of a box to check or terminology to use to indicate the slide which corresponds to the pinned insect.

**Comment by PipBrewer** [comment] 2023-10-25 08:05
This is a duplicate of issue NHMD Entomology - Connecting pinned insects with slides prepared from the same specimen #367
Opened in [NHMDenmark/Mass-Digitizer](https://github.com/NHMDenmark/Mass-Digitizer)

**Closed by PipBrewer** 2023-10-25 08:05 UTC
